services:
  odoo:
    image: odoo:latest
    ports:
      - "8069:8069"
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "5432:5432"
    volumes:
      - ./datos:/var/lib/postgresql/data